version: '3.5'

services:
  texlive:

    # image: qmcgaw/latexdevcontainer

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock 

    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: zsh -c "while sleep 1000; do :; done"
 