version: '3.5'

services:
  texlive:

    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ../:/workspace:Z
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: zsh -c "while sleep 1000; do :; done"
